name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Update APT
        run: sudo apt-get update

      - name: Install dependencies
        run: sudo apt-get install dbus-x11 libglib2.0-dev libjson-glib-dev libpolkit-gobject-1-dev meson ninja-build

      - name: Meson
        run: meson _build

      - name: Test
        run: ninja -C _build test
